services:
  # База данных
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
    networks:
      - app-network

  web:
    build: 
      context: .
      dockerfile: ./web/Dockerfile
    # command: sh -c "cd app && python manage.py collectstatic --noinput && gunicorn core.wsgi:application --bind 0.0.0.0:"
    command: sh -c "cd app && python manage.py runserver 0.0.0.0:"
    volumes:
      - ./web:/app
      - static_volume:/app/static
    ports:
      - "8000:8000"
    depends_on:
      - db
      - bot
    environment:
      - MAIN_HOST=laianbotrus.ru
      - MAIN_URL=http://laianbotrus.ru
      - SUPERUSER_PASS=1124816
      - SUPERUSER_NAME=admin
      - SUPERUSER_EMAIL=zaharowanrew@gmail.com 
      - USE_SSL=false
      - USE_DEBUG_MODE=false
      - DB_USER=postgres
      - DB_PASSWORD=qwerty
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DJANGO_SECRET_KEY=aDSFHGOIHihiouPIUiuedf23787823__!!!
      - BOT_API_URL=http://bot:8080
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - static_volume:/usr/share/nginx/html/static
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - app-network

  bot:
    build:
      context: .
      dockerfile: ./bot/Dockerfile
    command: python main.py
    volumes:
      - ./bot:/app
    environment:
      - BOT_TOKEN=7570491150:AAEmBEoVdq4I8laut3im76RP95xPHoulEQ8
      - MAIN_HOST=localhost
      - MAIN_PORT=8080
    networks:
      - app-network

volumes:
  postgres_data:
  static_volume: 

networks:
  app-network:
    driver: bridge