# Generated by Django 5.1.2 on 2024-11-03 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cost',
            new_name='price',
        ),
    ]
