# Generated by Django 5.1.2 on 2024-11-03 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_rename_cost_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='prime_category',
            field=models.BooleanField(default=False, verbose_name='Не относится к брендам'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.brand'),
        ),
    ]
