# Generated by Django 5.1.2 on 2024-11-17 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0004_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
    ]
