# Generated by Django 5.1.2 on 2024-11-03 16:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0004_category_prime_category_alter_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(default='неизвестно', max_length=55, verbose_name='Страна производитель'),
        ),
        migrations.AddField(
            model_name='product',
            name='volumes',
            field=models.CharField(default=django.utils.timezone.now, max_length=55, verbose_name='Объемы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='prime_category',
            field=models.BooleanField(default=False, verbose_name='Локальная категория'),
        ),
    ]
