# Generated by Django 5.1.2 on 2024-11-03 16:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0005_product_country_product_volumes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type_of_product',
            field=models.CharField(default=django.utils.timezone.now, max_length=55, verbose_name='Вид товара'),
            preserve_default=False,
        ),
    ]
