# Generated by Django 5.1.2 on 2024-11-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0006_product_type_of_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='type_of_product',
            field=models.CharField(max_length=22, verbose_name='Вид товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='volumes',
            field=models.CharField(max_length=22, verbose_name='Объемы'),
        ),
    ]
