# Generated by Django 5.1.2 on 2024-11-08 19:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0007_remove_cartitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimges',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.brand'),
        ),
        migrations.AddField(
            model_name='sliderimges',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
