# Generated by Django 5.1.2 on 2024-11-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0007_runningline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runningline',
            name='text',
            field=models.TextField(default=' - ', verbose_name='Текст бегущей строки'),
        ),
    ]
