# Generated by Django 5.1.2 on 2024-11-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0008_alter_runningline_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Настройки', max_length=50, null=True, verbose_name=' - ')),
                ('admin_id', models.CharField(max_length=255, null=True, verbose_name='Telegram Id (менеджер)')),
                ('main_channel_url', models.CharField(max_length=255, null=True, verbose_name='ссылка основного телеграм канала')),
                ('help_url', models.CharField(max_length=255, null=True, verbose_name='ссылка поддержки')),
                ('bot_url', models.CharField(verbose_name='ссылка бота')),
            ],
            options={
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.RemoveField(
            model_name='category',
            name='prime_category',
        ),
    ]
