# Generated by Django 5.1.2 on 2024-11-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0009_settings_remove_category_prime_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='admin_id',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Telegram Id (менеджер)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='bot_url',
            field=models.CharField(blank=True, default=' ', max_length=255, verbose_name='ссылка бота'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='help_url',
            field=models.CharField(blank=True, default=' ', max_length=255, verbose_name='ссылка поддержки'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='main_channel_url',
            field=models.CharField(blank=True, default=' ', max_length=255, verbose_name='ссылка основного телеграм канала'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='name',
            field=models.CharField(blank=True, default='Настройки', max_length=50, verbose_name=' - '),
        ),
    ]
