# Generated by Django 5.1.2 on 2024-11-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0010_alter_settings_admin_id_alter_settings_bot_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='admin_id',
            field=models.BigIntegerField(blank=True, default=None, null=True, verbose_name='Telegram Id (менеджер)'),
        ),
    ]
