# Generated by Django 5.1.2 on 2024-12-01 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0011_alter_settings_admin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderimges',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.brand'),
        ),
    ]
